name: Create and publish a Docker image
on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for vx-doc
        id: docmeta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/voxxlr/vx-doc

      - name: Build and push vx-doc image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./doc/Dockerfile
          push: true
          tags: ${{ steps.docmeta.outputs.tags }}
          labels: ${{ steps.docmeta.outputs.labels }}

      - name: Extract metadata for vx-app
        id: appmeta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/voxxlr/vx-app

      - name: Build and push vx-app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.appmeta.outputs.tags }}
          labels: ${{ steps.appmeta.outputs.labels }}

      - name: Extract metadata for vx-www
        id: wwwmeta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/voxxlr/vx-www

      - name: Build and push vx-www image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./www/Dockerfile
          push: true
          tags: ${{ steps.wwwmeta.outputs.tags }}
          labels: ${{ steps.wwwmeta.outputs.labels }}
